const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log("🔄 Resetting database...");

  // Clear existing data
  await prisma.$transaction([
    prisma.productDetail.deleteMany(),
    prisma.productOverview.deleteMany(),
    prisma.product.deleteMany(),
    prisma.category.deleteMany(),
    prisma.brand.deleteMany(),
    prisma.location.deleteMany(),
    prisma.news.deleteMany(),
  ]);

  console.log("✅ Database cleared. Seeding new data...");

  // Seed Categories
  const categories = await prisma.category.createMany({
    data: [
      { name: "Plumbing", slug: "main-plumbing" },
      { name: "Heating", slug: "main-heating" },
      { name: "HVAC/R", slug: "main-hvacr" },
      { name: "Propane", slug: "main-propane" },
      { name: "Pipe & Tube", slug: "main-pipe" },
      { name: "Electrical", slug: "main-electrical" },
      { name: "Fire Protection", slug: "fire-protection" },
      { name: "Fittings", slug: "main-fittings" },
      { name: "Hangers", slug: "main-hangers" },
      { name: "Hardware", slug: "main-hardware" },
      { name: "Industrial", slug: "main-industrial" },
      { name: "Safety", slug: "main-safety" },
      { name: "Specialties", slug: "specialties" },
      { name: "Tools", slug: "main-tools" },
      { name: "Valves", slug: "main-valves" },
      { name: "Well Systems", slug: "well-systems" },
    ],
  });

  // Seed Brands
  const brands = await prisma.brand.createMany({
    data: [
      { name: "3M Products", slug: "3m" },
      { name: "Airco", slug: "airco" },
      { name: "Aker", slug: "aker" },
      { name: "American Standard", slug: "american-standard" },
      { name: "Amtrol", slug: "amtrol" },
      { name: "Apollo", slug: "apollo" },
      { name: "Armstrong", slug: "armstrong" },
      { name: "Armstrong Pump", slug: "armstrong-pump" },
      { name: "Asco", slug: "asco" },
      { name: "Ashcroft", slug: "ashcroft" },
      { name: "Atco Rubber", slug: "atco-rubber" },
      { name: "AY Mcdonald", slug: "ay-mcdonald" },
      { name: "Banjo", slug: "banjo" },
      { name: "Bard", slug: "bard" },
      { name: "Barnes & Jones", slug: "barnes-and-jones" },
      { name: "Basco", slug: "basco" },
      { name: "Beacon Morris", slug: "beacon-morris" },
      { name: "Belimo", slug: "belimo" },
      { name: "Bell & Gossett", slug: "bell-and-gossett" },
      { name: "Blackstone", slug: "blackstone" },
      { name: "Blanco", slug: "blanco" },
      { name: "Blue-White", slug: "blue-white" },
      { name: "Bonney Forge", slug: "bonney-force" },
      { name: "Bonomi", slug: "bonomi" },
      { name: "Bosch", slug: "bosch" },
      { name: "Boss", slug: "boss" },
      { name: "Boyertown", slug: "boyertown" },
      { name: "Bradford White", slug: "bradford-white" },
      { name: "Brasscraft", slug: "brasscraft" },
      { name: "Brizo", slug: "brizo" },
      { name: "Broilmaster", slug: "broilmaster" },
      { name: "Buderus", slug: "buderus" },
      { name: "Burnham", slug: "burnham" },
      { name: "Caleffi", slug: "caleffi" },
      { name: "Calgon", slug: "calgon" },
      { name: "Cambridge Brass", slug: "cambridge-brass" },
      { name: "Carlin", slug: "carlin" },
      { name: "Cavagna", slug: "cavagna" },
      { name: "Centerline", slug: "centerline" },
      { name: "Central Brass", slug: "central-brass" },
      { name: "Centrotherm", slug: "centrotherm" },
      { name: "Chandler", slug: "chandler" },
      { name: "Channellock", slug: "channellock" },
      { name: "Chicago Faucet", slug: "chicago-faucet" },
      { name: "Church", slug: "church" },
      { name: "Clow Valve", slug: "clow-valve" },
      { name: "Conbraco", slug: "conbraco" },
      { name: "Copeland", slug: "copeland" },
      { name: "Crane", slug: "crane" },
      { name: "Crown", slug: "crown" },
      { name: "Dearborn", slug: "dearborn" },
      { name: "Delavan", slug: "delavan" },
      { name: "Delta", slug: "delta" },
      { name: "Dewalt", slug: "dewalt" },
      { name: "Diversitech", slug: "diversitech" },
      { name: "Dormont", slug: "dormont" },
      { name: "Dornbracht", slug: "dornbracht" },
      { name: "Dresser TPS", slug: "dresser" },
      { name: "Duravent", slug: "duravent" },
      { name: "Duravit", slug: "duravit" },
      { name: "DXV", slug: "dxv" },
      { name: "Elkay", slug: "elkay" },
      { name: "Empire", slug: "empire" },
      { name: "Fasco", slug: "fasco" },
      { name: "Fernco", slug: "fernco" },
      { name: "Fiat", slug: "fiat" },
      { name: "Field Controls", slug: "field-controls" },
      { name: "First Co.", slug: "first-co" },
      { name: "Flexcon", slug: "flexcon" },
      { name: "Flex-Hose", slug: "flex-hose" },
      { name: "Fluidmaster", slug: "fluidmaster" },
      { name: "Franke", slug: "franke" },
      { name: "Generac", slug: "generac" },
      { name: "General Electric", slug: "general-electric" },
      { name: "General Wire", slug: "general-wire" },
      { name: "Georg Fischer", slug: "georg-fischer" },
      { name: "Gerber", slug: "gerber" },
      { name: "Goulds", slug: "goulds" },
      { name: "Governale", slug: "governale" },
      { name: "Grohe", slug: "grohe" },
      { name: "Green Drain", slug: "green-drain" },
      { name: "Grundfos", slug: "grundfos" },
      { name: "Haier", slug: "haier" },
      { name: "Hansgrohe", slug: "hansgrohe" },
      { name: "Hart & Cooley", slug: "hart-and-cooley" },
      { name: "Hayward", slug: "hayward" },
      { name: "HB Smith", slug: "hb-smith" },
      { name: "Hercules", slug: "hercules" },
      { name: "Hoffman", slug: "hoffman" },
      { name: "Holdrite", slug: "holdrite" },
      { name: "Honeywell Home", slug: "honeywell-home" },
      { name: "HTP", slug: "htp" },
      { name: "Ideal", slug: "ideal" },
      { name: "InSinkErator", slug: "insinkerator" },
      { name: "Intellihot", slug: "intellihot" },
      { name: "IPEX", slug: "ipex" },
      { name: "IPS", slug: "ips" },
      { name: "Johnson Controls", slug: "johnson-controls" },
      { name: "Jomar", slug: "jomar" },
      { name: "Kamstrup", slug: "kamstrup" },
      { name: "Kennedy", slug: "kennedy" },
      { name: "Klein", slug: "klein" },
      { name: "Kunkle", slug: "kunkle" },
      { name: "Laars", slug: "laars" },
      { name: "Legend", slug: "legend" },
      { name: "Lenox", slug: "lenox" },
      { name: "Liberty", slug: "liberty" },
      { name: "Little Giant", slug: "little-giant" },
      { name: "LMI", slug: "lmi" },
      { name: "Lochinvar", slug: "lochinvar" },
      { name: "Louisville Ladder", slug: "louisville-ladder" },
      { name: "M&H", slug: "mandh" },
      { name: "Maax", slug: "maax" },
      { name: "Mansfield", slug: "mansfield" },
      { name: "Mars", slug: "mars" },
      { name: "Marshall Excelsior", slug: "marshall-excelsior" },
      { name: "Masoneilan", slug: "masoneilan" },
      { name: "Mcdonnell Miller", slug: "mcdonnell-miller" },
      { name: "McElroy", slug: "mcelroy" },
      { name: "McGuire", slug: "mcguire" },
      { name: "Miller Furnace", slug: "miller-furnace" },
      { name: "Millrose", slug: "millrose" },
      { name: "Milwaukee Tool", slug: "milwaukee-tools" },
      { name: "Milwaukee Valve", slug: "milwaukee-valve" },
      { name: "Modine", slug: "modine" },
      { name: "Moen", slug: "moen" },
      { name: "Mustee", slug: "mustee" },
      { name: "Myson", slug: "myson" },
      { name: "Navac", slug: "navac-brand" },
      { name: "Navien", slug: "navien" },
      { name: "Newport Brass", slug: "newport-brass" },
      { name: "Nibco", slug: "nibco" },
      { name: "Nortek", slug: "nortek" },
      { name: "Nupi", slug: "nupi" },
      { name: "Oasis", slug: "oasis" },
      { name: "Oatey", slug: "oatey" },
      { name: "Oil Equipment Manufacturing", slug: "oil-equipment-manufacturing" },
      { name: "Panasonic", slug: "panasonic" },
      { name: "Peerless", slug: "peerless" },
      { name: "Plastomatic", slug: "plastomatic" },
      { name: "Powell", slug: "powell" },
      { name: "Powers", slug: "powers" },
      { name: "Prier", slug: "prier" },
      { name: "PurePro", slug: "purepro" },
      { name: "Purmo", slug: "purmo" },
      { name: "Quiet One", slug: "quiet-one" },
      { name: "R.W. Beckett", slug: "beckett" },
      { name: "Rectorseal", slug: "rectorseal" },
      { name: "Red White", slug: "red-white" },
      { name: "Reed", slug: "reed" },
      { name: "Refrigeration Technologies", slug: "refrigeration-technologies" },
      { name: "Resideo", slug: "resideo" },
      { name: "Resistoflex", slug: "resistoflex" },
      { name: "Reznor", slug: "reznor" },
      { name: "Rheem", slug: "rheem" },
      { name: "RH Peterson", slug: "rh-peterson" },
      { name: "Ridgid", slug: "ridgid" },
      { name: "Riello", slug: "riello" },
      { name: "Rinnai", slug: "rinnai" },
      { name: "Ritchie", slug: "ritchie" },
      { name: "Robertshaw", slug: "robertshaw" },
      { name: "Rohl", slug: "rohl" },
      { name: "Roth", slug: "roth" },
      { name: "Runtal", slug: "runtal" },
      { name: "Saniflo", slug: "sfa-saniflo" },
      { name: "Samsung", slug: "samsung" },
      { name: "Sharpe", slug: "sharpe" },
      { name: "Signet", slug: "signet" },
      { name: "Sioux Chief", slug: "sioux-chief" },
      { name: "Sloan", slug: "sloan" },
      { name: "Smith-Blair", slug: "smith-blair" },
      { name: "Spacepak", slug: "spacepak" },
      { name: "Speakman", slug: "speakman" },
      { name: "Spears", slug: "spears" },
      { name: "Spence", slug: "spence" },
      { name: "Spirax-Sarco", slug: "spirax-sarco" },
      { name: "Sporlan", slug: "sporlan" },
      { name: "Sterling", slug: "sterling" },
      { name: "Strahman", slug: "strahman" },
      { name: "SVF", slug: "svf" },
      { name: "Swan", slug: "swan" },
      { name: "Symmons", slug: "symmons" },
      { name: "T&S Brass", slug: "tands-brass" },
      { name: "Taco", slug: "taco" },
      { name: "Tectite", slug: "tectite" },
      { name: "Tecumseh", slug: "tecumseh" },
      { name: "Tekmar", slug: "tekmar" },
      { name: "Testo", slug: "testo" },
      { name: "Thermo Pride", slug: "thermo-pride" },
      { name: "Toto", slug: "toto" },
      { name: "TracPipe", slug: "tracpipe" },
      { name: "Trerice", slug: "trerice" },
      { name: "Turbo Torch", slug: "turbo-torch" },
      { name: "Tylok", slug: "tylok" },
      { name: "Uponor", slug: "uponor" },
      { name: "US Motors", slug: "us-motor" },
      { name: "Valex", slug: "valex" },
      { name: "Vaughn", slug: "vaughn" },
      { name: "Victaulic", slug: "victaulic" },
      { name: "Watts", slug: "watts" },
      { name: "Watts Radiant Pex", slug: "watts-radiant-pex"},
      { name: "Watts Water Pex", slug: "watts-water-pex"},
      { name: "Webstone", slug: "webstone"},
      { name: "Weil Mclain", slug: "weil-mclain"},
      { name: "Westwood", slug: "westwood"},
      { name: "White Mountain Hearth", slug: "white-mountain-hearth"},
      { name: "White Rodgers", slug: "white-rodgers "},
      { name: "York", slug: "york"},
      { name: "Z Flex", slug: "z-flex "},
      { name: "Zoeller", slug: "zoeller"},
    ],
  });

  // Seed Locations
  const locations = await prisma.location.createMany({
    data: [
      {
        city: "Danbury",
        state: "CT",
        storeName: "F.W. Webb Company",
        address: "28 Finance Dr, Danbury, CT 06810",
        phone: "203-748-2635",
        hours: JSON.stringify({
          Mon: "06:30 AM - 04:30 PM",
          Tue: "06:30 AM - 04:30 PM",
          Wed: "06:30 AM - 04:30 PM",
          Thu: "06:30 AM - 04:30 PM",
          Fri: "06:30 AM - 04:30 PM",
          Sat: "08:00 AM - 12:00 PM",
          Sun: "Closed",
        }),
        emergencyContact: null,
      },
      {
        city: "Brookfield",
        state: "CT",
        storeName: "Frank Webb Home",
        address: "317 Federal Road, Brookfield, CT 06804",
        phone: "203-775-5050",
        hours: JSON.stringify({
          Mon: "08:30 AM - 05:00 PM",
          Tue: "08:30 AM - 12:00 PM",
          Wed: "Closed",
          Thu: "08:30 AM - 05:00 PM",
          Fri: "08:30 AM - 05:00 PM",
          Sat: "08:00 AM - 02:00 PM",
          Sun: "Closed",
        }),
        emergencyContact: null,
      },
    ],
  });

  // Seed Products with Details and Overviews
  const product = await prisma.product.create({
    data: {
      name: "Two Handle Bar Faucet",
      description: "Two Handle 4\" Centerset Bar Faucet with Wrist Blade Handles - Polished Chrome",
      price: 128.06,
      slug: "two-handle-bar-faucet",
      modelNumber: "33518-TP",
      productNumber: "1103520",
      Brand: {
        connect: { slug: "purepro" } // Connect by unique field (e.g., slug)
      },
      Category: {
        connect: { slug: "main-plumbing" } // Connect by unique field (e.g., slug)
      },
      overviews: {
        create: [
          { content: "1.75 gpm" },
          { content: "Finish: Polished Chrome" },
          { content: "Metal lever handles" },
        ],
      },
      details: {
        create: [
          { key: "Brand", value: "PurePro" },
          { key: "Shipping Weight", value: "6.000 LBS" },
        ],
      },
    },
  });

  console.log("✅ Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed: ", e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
